- nes-systests/systest/include/SystestRunner.hpp
- nes-systests/systest/include/SystestState.hpp
- nes-systests/systest/src/SystestRunner.cpp
- nes-systests/systest/src/SystestState.cpp
This pull request fixes the throughput of the query performance message printed to stdout. 
- There is no test to verify this change, however, one can manually check the printed message
> fix(Systest): fix throughput in query performance output

- nes-common/include/Identifiers/Identifiers.hpp
- nes-logical-operators/src/Serialization/OperatorSerializationUtil.cpp
- nes-sources/include/Sources/SourceCatalog.hpp
- nes-sources/include/Sources/SourceDescriptor.hpp
- nes-sources/src/SourceCatalog.cpp
- nes-sources/src/SourceDescriptor.cpp
- nes-sources/tests/SourceCatalogTest.cpp
This PR changes the physical source id in the `SinkDescriptor` from a uint64_t to a newly created `PhysicalSourceId` strong type, and also updates all of its usages. 
The code compiles, and all systests + all unit tests including the sources tests succeed.
Sources, Optimizer
This PR closes #914
> chore(sources): add PhysicalSourceId strong type

- .github/workflows/get_dev_images.yml
- docker/dependency/Development.dockerfile
Addresses a problem in this run: https://github.com/nebulastream/nebulastream/actions/runs/15618047064/job/44003945776
The _"is this image already on dockerhub"_ check queries dockerhub which return `500 - Internal Server Error`, which is interpreted as _"image not yet on dockerhub, let's build and push"_. I think it would be better to either retry and/or be explicit about this dockerhub fail.
This also simplifies the check: Instead of getting a list of tags and checking if it contains the one we want we directly use the corresponding dockerhub API endpoint.
---
btw afaics the build steps are then failing for an independent reason, I think this is due to `--cache-from type=registry,ref=nebulastream/nes-development-base-cache:-x64` aka the `inputs.branch-name` in `get_dev_images.yml` is …
> ci: improve 'is image on dockerhub' check

- nes-query-optimizer/src/CMakeLists.txt
- nes-query-optimizer/src/QueryOptimizer.cpp
File contains `QueryOptimizer` and references `QueryOptimizer.hpp` but was `QueryCompiler.cpp`.
This PR fixes this.
> fix QueryOptimizer.cpp filename

- nes-systests/systest/src/QuerySubmitter.cpp
- nes-systests/systest/src/SystestStarter.cpp
This PR changes the localquerysubmitter to actually use the serialization logic, which catches bad serialization logic in our systests.
> test(Systest): Use serialization logic in systest

- nes-memory/UnpooledChunksManager.cpp
Reduce the log message for "added tuple buffer" in the unpooled chunks manager to trace from info.
> chore(BufferManager): UnpooledChunks reduce log levels

- nes-runtime/include/Configuration/WorkerConfiguration.hpp
Currently, the nightly CI fails because it runs out of buffers. This PR increases the default number of buffers allocated on
startup, which circumvents the issue.
The proper solution would be to implement buffer spilling.
This change increases the default allocation from 4Mb to 131Mb
> chore(SingleNodeWorker): Increases default number of buffers

- nes-systests/systest/src/SystestRunner.cpp
The pull request fixes an oversight where each runningQuery is inserted twice into the ranQueries vector in runQueriesAndBenchmark (SystestRunner).
As a result of this, two identical results for every ran query were published to the Conbench server.
This change is tested by
- systest with -b still produces the desired BenchmarkResults.json, but without duplicates.
- nes-systests
This PR closes #1016
> Removed double insertion of runningQuery in ranQueries vector in runQueriesAndBenchmark

- nes-plugins/Sources/GeneratorSource/GeneratorFields.hpp
- nes-plugins/Sources/GeneratorSource/GeneratorSource.cpp
- nes-systests/sources/Generator.test
- nes-systests/systest-sources/include/SystestSources/SourceTypes.hpp
- nes-systests/systest/include/SystestParser.hpp
- nes-systests/systest/src/SystestBinder.cpp
- nes-systests/systest/src/SystestParser.cpp
- nes-systests/systest/tests/SystestParserValidTestFilesTests.cpp
This PR addes the ability to define a GeneratorSource within a Systest file, without needing to specific an additional config
The syntax is the following:
```
Source generatorDefault UINT64 id UINT64 double UINT64 sourceOnly GENERATOR seed 1, maxRuntimeMS 1000, stopGeneratorWhenSequenceFinishes ALL
id SEQUENCE UINT64 0 10 1
double SEQUENCE UINT64 0 5 1
```
Additionally there is logic to the catch the following wrongly defined GeneratorSources
- Number of fields defined does not match number of defined generator field schemas
- Type of generator field schema is not a type that generator field supports
- Type of field defined does not match type defined in generator field schema
- Field defined does not have an accompanying identically named generator field schema
Adding …
> feat(Systest): Add inline definition for GeneratorSource

- nes-systests/systest/CMakeLists.txt
Fixes a wrong path in the cmake for large scale systests.
I am wondering how this passed the CI?
> fix(systest): large scale data path

- nes-nebuli/private/YAML/YAMLBinder.hpp
- nes-nebuli/src/YAML/YAMLBinder.cpp
Small hotfix that binds sinks and sources correctly from yaml files now.
One slightly bigger change is that types of physical sources are not in the top-level configuration of them, not in the sourceConfig section anymore.
> fix(yamlbinder): fix binding of sources and sinks

- nes-nebuli/CMakeLists.txt
- nes-nebuli/include/Repl.hpp
- nes-nebuli/src/NebuLIStarter.cpp
- nes-nebuli/src/Repl.cpp
- vcpkg/vcpkg.json
The REPL can be started with the following command: `nebuli repl --server <address>`
The interactive terminal supports issuing the following commands:
```
Available commands:
help     - Show this help message
list     - List active queries
stop <id> - Stop a specific query by ID
clear    - Clear the screen
quit     - Exit the REPL
exit     - Exit the REPL
You can also enter SQL queries directly.
Multi-line queries are supported.
```
Clion with docker setup has shown some problems with the replxx library. 
This can be circumvented by start the REPL via: `nebuli repl --server <address> --non-interactive`
> Nebuli REPL Support

- .github/workflows/clang_tidy_full.yml
- nes-common/tests/UnitTests/Util/NonBlockingMonotonicSeqQueueTest.cpp
- nes-configurations/src/Configurations/Descriptor.cpp
- nes-data-types/src/DataTypes/TimeUnit.cpp
- nes-data-types/src/Serialization/DataTypeSerializationUtil.cpp
- nes-executable/src/Pipeline.cpp
- nes-physical-operators/src/Join/NestedLoopJoin/NLJSlice.cpp
- nes-query-compiler/src/PipelinedQueryPlan.cpp
- nes-sinks/src/PrintSink.cpp
- nes-sinks/src/SinkDescriptor.cpp
- nes-sinks/src/SinksParsing/CSVFormat.cpp
- nes-sql-parser/src/AntlrSQLQueryParser.cpp
- nes-systests/systest/src/SystestState.cpp
- nes-systests/systest/tests/SystestRunnerTest.cpp
Ensures that clang-tidy violations fail the nightly pipeline and fixes some violations.
> Clang tidy fixes

- nes-systests/systest/src/SystestRunner.cpp
As `bytesProcessed` is an uint64_t if the optional has no value this would result in the defined NAN macro being cast to uint64_t and then being cast to double. The end result not being a NAN double. The same for `tuplesProcessed`
> fix(Systest): serializeExecutionResults to NAN if no value in optional

- nes-logical-operators/src/Operators/Sinks/SinkLogicalOperator.cpp
- nes-systests/systest/tests/SystestRunnerTest.cpp
Prior, 'getOutputSchema()' returned the schema of the first child operator. This could lead to errors, especially in the proof of concept branch for running NES distributed.
> fix(SinkLogicalOperator): taking output schema from descriptor

- .github/workflows/code_coverage.yml
- .github/workflows/pr-merge.yml
Apparently the merge pr job associated the coverage with the wrong branch.
Hopefully this PR fixes the issue, and both uses the new commit sha (the sha changes when you rebase and merge) and also uses the main branch instead of the pr branches name.
I wish you could
Code coverage reporting
> Fix CodeCov using the wrong base commit

- nes-executable/include/CompiledQueryPlan.hpp
- nes-input-formatters/include/InputFormatters/InputFormatterProvider.hpp
- nes-input-formatters/private/InputFormatterTask.hpp
- nes-input-formatters/registry/include/InputFormatIndexerRegistry.hpp
- nes-input-formatters/src/InputFormatterProvider.cpp
- nes-input-formatters/tests/Util/InputFormatterTestUtil.cpp
- nes-input-formatters/tests/Util/InputFormatterTestUtil.hpp
- nes-query-compiler/private/Phases/LowerToCompiledQueryPlanPhase.hpp
- nes-query-compiler/src/Phases/LowerToCompiledQueryPlanPhase.cpp
- nes-runtime/src/ExecutableQueryPlan.cpp
This pull request adds support for variable sized data to the nested loop join. The change list is as follows:
- Removed `originId` information from formatters completely. Input formatters set the origin ids of their output buffers entirely based on the input buffers they receive, therefore its not necessary to provide them with one during lowering.
- Exchanged the use of `originId` in the pipelining phase. They were used to detect source->sink type forwarding queries. For this, `OperatorId` serves the same purpose and it enables us to use multiple origin ids per source in the future. 
This change is tested by
- Existing test suite
- Formatters: 
- No additional documentation required
This PR closes #1097.
> chore(OriginId): remove `OriginId` from formatters, replace with `OperatorId` to detect source -> sink pipelines

- nes-systests/systest/CMakeLists.txt
We missed one large scale benchmark when changing parameters to snake case, this fixes it.
> fix(benchmarks): missing snake case parameter

- .mailmap
- scripts/check_preamble.py
[git docs for mailmap](https://git-scm.com/docs/gitmailmap)
```
$ git shortlog --after=2025-01-01 | grep "^[^ ]"
Adrian Michalke (240):
Benjamin Greb (6):
Eric Benschneider (15):
Klaas tom Dieck (16):
Kyle Krueger (4):
Kyle Krüger (1):
Leo Raasch (15):
Leonhard Rose (24):
Lukas Schwerdtfeger (33):
Matthis Gördel (221):
Niklas Tantow (7):
Nils L. Schubert (52):
Nils Schubert (120):
Philipp-Timm (8):
Sara Lhamo Schnaterbeck (1):
Tilman (2):
Tim Nacken (16):
Yanikovic (9):
Yannik Schröder (1):
alepping (120):
aljoscha lepping (1):
fkuzun (1):
greenBene (1):
lukas schwerdtfeger (153):
nikla44 (1):
nmlt (5):
tdietzel@beaver (1):
tekdogan (5):
```
```sh
$ git shortlog --after=2025-01-01 | grep "^[^ ]"
Adrian Michalke (240):
Aljoscha Lepping (121):
Benedikt Beckermann (1):
Benjamin Greb (6): …
```
> add .mailmap file to canonize git author names and mail addresses

- .github/workflows/execute_query.yml
- .github/workflows/pr.yml
- nes-plugins/Sources/GeneratorSource/GeneratorFields.cpp
The execute query ci job was not updated according to the new emit_rate generator source configuration.
CI Passes again
- CI
> hotfix(CI): Adds missing emit rate configuration

- nes-plugins/Sources/TCPSource/TCPSource.cpp
- nes-systests/bug/NotInJoinPredicate.test.disabled
- nes-systests/differential/AggregationEquiValence.test
- nes-systests/differential/JoinEquivalence.test
- nes-systests/differential/ProjectionEquivalence.test
- nes-systests/differential/SelectionEquivalence.test
- nes-systests/systest/include/SystestParser.hpp
- nes-systests/systest/include/SystestState.hpp
- nes-systests/systest/src/SystestBinder.cpp
- nes-systests/systest/src/SystestParser.cpp
- nes-systests/systest/src/SystestResultCheck.cpp
- nes-systests/systest/src/SystestRunner.cpp
- nes-systests/systest/src/SystestState.cpp
- nes-systests/systest/tests/SystestParserInvalidTestFilesTests.cpp
- nes-systests/systest/tests/SystestParserTests.cpp
- nes-systests/systest/tests/SystestRunnerTest.cpp
- nes-systests/systest/tests/testdata/differential.dummy
- nes-systests/systest/tests/testdata/invalid_differential.dummy
This pull request adds differential testing support to our systests, i.e. running two semantically equivalent queries for a certain amount of time and check for equivalent results.
Example Syntax:
```SQL
SELECT id * UINT32(10) AS id, value, timestamp FROM stream INTO streamSink
====
SELECT id * UINT32(2) * UINT32(5) AS id, value, timestamp FROM stream INTO streamSink
```
- added ability for SystestQueries to store an additional optional LogicalPlan for the second part of the differential query
- added `DIFFERENTIAL` token to avoid confusion with empty result fields for certain existing tests
This change is tested by
- InvalidDifferentialTest in SystestParserInvalidTestFilesTests.cpp using invalid_differential.dummy
- testDifferentialQueryCallbackFromFile in SystestParserTests.cpp using …
> feat(Systest): enable differential testing

- nes-common/include/ErrorHandling.hpp
- nes-common/include/Util/TypeTraits.hpp
- nes-common/tests/UnitTests/Util/CMakeLists.txt
- nes-common/tests/UnitTests/Util/TypeTraitsTest.cpp
- nes-query-engine/Interfaces.hpp
- nes-query-engine/QueryEngine.cpp
- nes-query-engine/RunningQueryPlan.cpp
- nes-query-engine/RunningQueryPlan.hpp
- nes-query-engine/RunningSource.cpp
- nes-query-engine/Task.cpp
- nes-query-engine/Task.hpp
- nes-query-engine/tests/QueryEngineTest.cpp
- nes-query-engine/tests/QueryPlanTest.cpp
- nes-query-engine/tests/Util/QueryEngineTestingInfrastructure.hpp
- nes-sources/tests/Util/TestSource.cpp
- nes-sources/tests/Util/TestSource.hpp
This PR addresses a race condition which could occur when a query start races with a query stop. 
The issue was caused by the pipelineSetupCallback which is used once all pipelines have been started, and is intended to start all sources, finding an already destroyed running query plan object. 
The running query plan object has been destroyed by a concurrent query stop.
The fix disables the callback (i.e. it is never called) before destroying the running query plan.
This means either the running query plan is destroyed before the callback is invoked, which will skip the callback, or the callback is invoked which will block the destructor of the running query plan until the callback completes.
The running query plan then has to stop the sources.
Additionally, this PR refactors the Task …
> Fix start/stop race condition in query engine 

- nes-logical-operators/include/Operators/Windows/Aggregations/AvgAggregationLogicalFunction.hpp
- nes-logical-operators/include/Operators/Windows/Aggregations/CountAggregationLogicalFunction.hpp
- nes-logical-operators/include/Operators/Windows/Aggregations/MaxAggregationLogicalFunction.hpp
- nes-logical-operators/include/Operators/Windows/Aggregations/MedianAggregationLogicalFunction.hpp
- nes-logical-operators/include/Operators/Windows/Aggregations/MinAggregationLogicalFunction.hpp
- nes-logical-operators/include/Operators/Windows/Aggregations/SumAggregationLogicalFunction.hpp
- nes-logical-operators/src/Operators/Windows/Aggregations/AvgAggregationLogicalFunction.cpp
- nes-logical-operators/src/Operators/Windows/Aggregations/CountAggregationLogicalFunction.cpp
- nes-logical-operators/src/Operators/Windows/Aggregations/MaxAggregationLogicalFunction.cpp
- nes-logical-operators/src/Operators/Windows/Aggregations/MedianAggregationLogicalFunction.cpp
- nes-logical-operators/src/Operators/Windows/Aggregations/MinAggregationLogicalFunction.cpp
- nes-logical-operators/src/Operators/Windows/Aggregations/SumAggregationLogicalFunction.cpp
- nes-sql-parser/src/AntlrSQLQueryPlanCreator.cpp
The create method is a remnant of the old API and we instead use std::make_shared directly.
It compiles, so no usage of the create methods remains.
Aggregations
n/a
> chore(Aggregations): Replace create method with std::make_shared

- nes-common/CMakeLists.txt
- nes-common/include/Util/UUID.hpp
- nes-common/src/Util/CMakeLists.txt
- nes-common/src/Util/UUID.cpp
- nes-common/tests/Util/src/BaseIntegrationTest.cpp
- vcpkg/vcpkg.json
Adds libuuid to generate uuids securely
This is part of the distributed upstreaming
> chore(Dependencies): adds libuuid

- .clang-tidy
- nes-plugins/Sources/GeneratorSource/GeneratorFields.hpp
- disables [cert-err60-cpp](https://clang.llvm.org/extra/clang-tidy/checks/cert/err60-cpp.html) which afaics conflicts with using `cpptrace::lazy_exception`.
- removes duplicate include
> Fix clang tidy

- .github/.env/test-thread.env
- .github/.env/tsan_suppressions.txt
- nes-common/include/ExceptionDefinitions.inc
- nes-executable/include/PipelineExecutionContext.hpp
- nes-executable/tests/TestUtils/TestTaskQueue.cpp
- nes-executable/tests/TestUtils/TestTaskQueue.hpp
- nes-input-formatters/private/InputFormatterTask.hpp
- nes-input-formatters/private/RawTupleBuffer.hpp
- nes-physical-operators/tests/EmitPhysicalOperatorTest.cpp
- nes-query-engine/DelayedTaskSubmitter.hpp
- nes-query-engine/QueryEngine.cpp
- nes-query-engine/QueryEngineConfiguration.cpp
- nes-query-engine/Task.cpp
- nes-query-engine/Task.hpp
- nes-query-engine/TaskQueue.hpp
- nes-query-engine/include/QueryEngineConfiguration.hpp
- nes-query-engine/tests/CMakeLists.txt
- nes-query-engine/tests/DelayedTaskSubmitterTest.cpp
- nes-query-engine/tests/QueryEngineConfigurationTest.cpp
- nes-query-engine/tests/QueryEngineTest.cpp
- nes-query-engine/tests/QueryPlanTest.cpp
- nes-query-engine/tests/TaskQueueTest.cpp
- nes-query-engine/tests/Util/QueryEngineTestingInfrastructure.hpp
- nes-systests/systest/CMakeLists.txt
**fix(engine): Suppresses a harmless lock inversion report**
The TSAN CI reports a lock inversion in the query engine. Unfortunately, there is no trivial change that could remove the lock inversion. The lock inversion will also never (I regret writing that) cause a deadlock, as currently, both code paths cannot run concurrently. One code path is called from the StartQueryTask, and the other one is called in a callback after all pipelines have been set up. The start task prevents the callback from triggering while it is holding the lock.
feat(engine): Adds DelayedTaskSubmitter
This commit introduces a new Active Component into the QueryEngine, which manages a queue of tasks that should be submitted at a later point. The component is mostly inactive, waiting for either a timer or new tasks …
> Addresses TaskQueue Polling and improves repeated tasks
